### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by Lucero7919** [schnerring/terraform-azurerm-aadds#1]
The problem with GitHub is people mean well, but they can never truly stay on top of their projects.

This module is missing and ABSOLUTE terraform requirement
│ Error: Missing required argument
│
│   with module.aadds.azuread_group.aadds,
│   on .terraform\modules\aadds\main.tf line 26, in resource "azuread_group" "aadds":
│   26: resource "azuread_group" "aadds" {
│
│ "mail_enabled": one of `mail_enabled,security_enabled` must be specified
╵
╷
│ Error: Missing required argument
│
│   with module.aadds.azuread_group.aadds,
│   on .terraform\modules\aadds\main.tf line 26, in resource "azuread_group" "aadds":
│   26: resource "azuread_group" "aadds" {
│
│ "security_enabled": one of `mail_enabled,security_enabled` must be specified

Additionally:

│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/hashicorp/azuread" requires explicit configuration. Add a provider block to the root module and configure the
│ provider's required arguments as described in the provider documentation.
│

Additionally, it's using an out of date provider (AzureAD 2.0 is now GA)

**Comment by schnerring** [comment]
> The problem with GitHub is people mean well, but they can never truly stay on top of their projects.

The nice thing about open-source is that other people can stay on top of other peoples projects ;-)

Thanks for the issue! I have already updated the blog post I wrote about this module. I now also added a deprecation notice to the README and archived the repo (should have done that initially as well, sorry about the confusion).

This module is no longer needed and all the functionality can be achieved with official Terraform providers.
